#ifndef __FPGA_CONFIG_H__
#define __FPGA_CONFIG_H__

// FPGA_SET00
#define FPGA_CONFIG0_GPIO_PORT GPIO4
#define FPGA_CONFIG0_GPIO_PIN (13U)

// FPGA_SET01
#define FPGA_CONFIG1_GPIO_PORT GPIO4
#define FPGA_CONFIG1_GPIO_PIN (14U)

// FPGA_SET02
#define FPGA_CONFIG2_GPIO_PORT GPIO2
#define FPGA_CONFIG2_GPIO_PIN (9U)

#define FPGA_CONF_DONE_GPIO_PORT GPIO3
#define FPGA_CONF_DONE_GPIO_PIN (2U)

#define FPGA_NSTATUS_GPIO_PORT GPIO3
#define FPGA_NSTATUS_GPIO_PIN (19U)

#define FPGA_NCONFIG_GPIO_PORT GPIO3
#define FPGA_NCONFIG_GPIO_PIN (20U)

#define FPGA_DATA0_GPIO_PORT GPIO6
#define FPGA_DATA0_GPIO_PIN (8U)

#define FPGA_DCLK_GPIO_PORT GPIO6
#define FPGA_DCLK_GPIO_PIN (9U)

#define FPGA_FIREWARM_FILE_PATH "/nac1010.rbf"
#define BUF_LEN 1024
#define CHECK_EVERY_X_BYTE 10240

#define INIT_CYCLE (2U)

int check_fpga_config(void);
int config_fpga_firmware(void);

#endif //__FPGA_CONFIG_H