/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

#define BOARD_INITPINS_IOMUXC_GPR_GPR43_GPIO_MUX3_GPIO_SEL_HIGH_MASK 0x0600U /*!< GPIO3 and CM7_GPIO3 share same IO MUX function, GPIO_MUX3 selects one GPIO function: affected bits mask */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);                    /* Function assigned for the Cortex-M7F */

#define BOARD_INITFPGACONFIGPINS_IOMUXC_GPR_GPR40_GPIO_MUX2_GPIO_SEL_LOW_MASK 0x0200U /*!< GPIO2 and CM7_GPIO2 share same IO MUX function, GPIO_MUX2 selects one GPIO function: affected bits mask */
#define BOARD_INITFPGACONFIGPINS_IOMUXC_GPR_GPR42_GPIO_MUX3_GPIO_SEL_LOW_MASK 0x04U /*!< GPIO3 and CM7_GPIO3 share same IO MUX function, GPIO_MUX3 selects one GPIO function: affected bits mask */
#define BOARD_INITFPGACONFIGPINS_IOMUXC_GPR_GPR43_GPIO_MUX3_GPIO_SEL_HIGH_MASK 0x18U /*!< GPIO3 and CM7_GPIO3 share same IO MUX function, GPIO_MUX3 selects one GPIO function: affected bits mask */

/* GPIO_AD_03 (coord P15), gpio3_02_pinP15 */
/* Routed pin properties */
#define BOARD_INITFPGACONFIGPINS_gpio3_02_pinP15_PERIPHERAL                GPIO3   /*!< Peripheral name */
#define BOARD_INITFPGACONFIGPINS_gpio3_02_pinP15_SIGNAL              gpio_mux_io   /*!< Signal name */
#define BOARD_INITFPGACONFIGPINS_gpio3_02_pinP15_CHANNEL                      2U   /*!< Signal channel */

/* GPIO_AD_20 (coord K13), gpio3_19_pinK13 */
/* Routed pin properties */
#define BOARD_INITFPGACONFIGPINS_gpio3_19_pinK13_PERIPHERAL                GPIO3   /*!< Peripheral name */
#define BOARD_INITFPGACONFIGPINS_gpio3_19_pinK13_SIGNAL              gpio_mux_io   /*!< Signal name */
#define BOARD_INITFPGACONFIGPINS_gpio3_19_pinK13_CHANNEL                     19U   /*!< Signal channel */

/* GPIO_AD_21 (coord K14), gpio3_20_pinK14 */
/* Routed pin properties */
#define BOARD_INITFPGACONFIGPINS_gpio3_20_pinK14_PERIPHERAL                GPIO3   /*!< Peripheral name */
#define BOARD_INITFPGACONFIGPINS_gpio3_20_pinK14_SIGNAL              gpio_mux_io   /*!< Signal name */
#define BOARD_INITFPGACONFIGPINS_gpio3_20_pinK14_CHANNEL                     20U   /*!< Signal channel */

/* GPIO_LPSR_09 (coord P5), gpio6_09_pinP5 */
/* Routed pin properties */
#define BOARD_INITFPGACONFIGPINS_gpio6_09_pinP5_PERIPHERAL                 GPIO6   /*!< Peripheral name */
#define BOARD_INITFPGACONFIGPINS_gpio6_09_pinP5_SIGNAL               gpio_mux_io   /*!< Signal name */
#define BOARD_INITFPGACONFIGPINS_gpio6_09_pinP5_CHANNEL                       9U   /*!< Signal channel */

/* GPIO_LPSR_08 (coord U8), gpio6_08_pinU8 */
/* Routed pin properties */
#define BOARD_INITFPGACONFIGPINS_gpio6_08_pinU8_PERIPHERAL                 GPIO6   /*!< Peripheral name */
#define BOARD_INITFPGACONFIGPINS_gpio6_08_pinU8_SIGNAL               gpio_mux_io   /*!< Signal name */
#define BOARD_INITFPGACONFIGPINS_gpio6_08_pinU8_CHANNEL                       8U   /*!< Signal channel */

/* GPIO_SD_B2_04 (coord F14), gpio4_13_pinF14 */
/* Routed pin properties */
#define BOARD_INITFPGACONFIGPINS_gpio4_13_pinF14_PERIPHERAL                GPIO4   /*!< Peripheral name */
#define BOARD_INITFPGACONFIGPINS_gpio4_13_pinF14_SIGNAL              gpio_mux_io   /*!< Signal name */
#define BOARD_INITFPGACONFIGPINS_gpio4_13_pinF14_CHANNEL                     13U   /*!< Signal channel */

/* GPIO_SD_B2_05 (coord E14), gpio4_14_pinE14 */
/* Routed pin properties */
#define BOARD_INITFPGACONFIGPINS_gpio4_14_pinE14_PERIPHERAL                GPIO4   /*!< Peripheral name */
#define BOARD_INITFPGACONFIGPINS_gpio4_14_pinE14_SIGNAL              gpio_mux_io   /*!< Signal name */
#define BOARD_INITFPGACONFIGPINS_gpio4_14_pinE14_CHANNEL                     14U   /*!< Signal channel */

/* GPIO_EMC_B1_41 (coord L1), gpio2_09_pinL1 */
/* Routed pin properties */
#define BOARD_INITFPGACONFIGPINS_gpio2_09_pinL1_PERIPHERAL                 GPIO2   /*!< Peripheral name */
#define BOARD_INITFPGACONFIGPINS_gpio2_09_pinL1_SIGNAL               gpio_mux_io   /*!< Signal name */
#define BOARD_INITFPGACONFIGPINS_gpio2_09_pinL1_CHANNEL                       9U   /*!< Signal channel */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitFPGAConfigPins(void);          /* Function assigned for the Cortex-M7F */

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
