from building import *

cwd = GetCurrentDir()

# add the general drivers.
src = Split("""
board.c
dcd.c
MCUX_Config/clock_config.c
MCUX_Config/pin_mux.c
""")

CPPPATH = [cwd,cwd + '/MCUX_Config',cwd + '/ports']
CPPDEFINES = ['CPU_MIMXRT1176DVMAA_cm7', 'XIP_BOOT_HEADER_ENABLE=0', 'XIP_BOOT_HEADER_DCD_ENABLE=0', 'FSL_SDK_ENABLE_DRIVER_CACHE_CONTROL=1','ARM_MATH_CM7','USE_SDRAM','SOC_IMXRT1170_SERIES',
                '__USE_SHMEM', 'DATA_SECTION_IS_CACHEABLE=1']

group = DefineGroup('Drivers', src, depend = [''], CPPPATH = CPPPATH, CPPDEFINES=CPPDEFINES)

Return('group')
